### ISSUE TITLE
implement dora.Get<T>()

### ISSUE THREAD

**Issue by dviramontes** [bradford-hamilton/dora#4]
- GetBool()
- GetFloat64(), JSON's only number type
- GetArray() or maybe Slice{} ?
- GetObject() or maybe Struct{} ?
- GetNull() ? for completeness ?

**Comment by bradford-hamilton** [comment]
@dviramontes I had to adjust the JSON parser a little bit for the float support, I totally forgot I never wrapped it up. In other words, you were not crazy about the test not passing - it was not correct.

**Comment by bradford-hamilton** [comment]
GetBool(), GetFloat64(), GetString() complete.
