### ISSUE TITLE
JSON-C support

### ISSUE THREAD

**Issue by stuartleeks** [bradford-hamilton/dora#6]
**Is your feature request related to a problem? Please describe:**

I'm looking for a package that allows me to parse and modify documents in JSON-C (JSON with Comments) form.

**Describe the solution you'd like:**

I'd love dora to support parsing JSON-C (and preserving the whitespace/comments in the internal structure), and to support modifying the document before writing it out again.

**Describe alternatives you've considered:**

I've started working on some code that builds on dora to add JSON-C support. I started it separately as I wasn't sure how well it would fit with the existing models, but from an early play it looks like it might be possible to extend dora to include these changes.

Would you be interested in this as a Pull Request? I.e. does it fit with your goal for dora, or should I keep it as separate package?

**Comment by bradford-hamilton** [comment]
Hey @stuartleeks, I'd be happy to look at a PR for JSON-C support! Unfortunately, I haven't had as much time recently for `dora`, so glad to see this come through.

**Comment by stuartleeks** [comment]
Cool, I'll see how it continues. The lexer wasn't too bad, but the parser required more changes and I'm just adding the dora package in now and getting that working.
My goal is to support parsing, modifying, and writing back JSON-C documents and preserving comments and existing formatting.

**Comment by stuartleeks** [comment]
I've just created #8 which updates the lexer and parser to handle comments. It also captures comments and whitespace to enable writing documents back with their original formatting. My next step is to work on the support for modifying and saving documents, but this PR felt like a sufficiently complete unit of work to let you take a look and see whether it is going in a direction that you are comfortable with for dora.  Thanks for your work creating dora!

**Comment by bradford-hamilton** [comment]
@stuartleeks thanks a bunch, very much appreciate your work! Just merged, happy to continue to look at PRs if you end up creating more.

**Comment by stuartleeks** [comment]
I've got some more changes to support merging documents in my fork. Will try to sort out sending you a PR to look at soon.

**Comment by bradford-hamilton** [comment]
Sounds good!
